INSERT INTO medications_catalog (name, is_custom, created_by_user_id, created_at) VALUES
('Paracetamol', 0, NULL, CURRENT_TIMESTAMP),
('Ibuprofeno', 0, NULL, CURRENT_TIMESTAMP),
('Aspirina', 0, NULL, CURRENT_TIMESTAMP),
('Amoxicilina', 0, NULL, CURRENT_TIMESTAMP),
('Losartán', 0, NULL, CURRENT_TIMESTAMP),
('Enalapril', 0, NULL, CURRENT_TIMESTAMP),
('Metformina', 0, NULL, CURRENT_TIMESTAMP),
('Omeprazol', 0, NULL, CURRENT_TIMESTAMP),
('Salbutamol', 0, NULL, CURRENT_TIMESTAMP),
('Loratadina', 0, NULL, CURRENT_TIMESTAMP),
('Cetirizina', 0, NULL, CURRENT_TIMESTAMP),
('Diclofenaco', 0, NULL, CURRENT_TIMESTAMP),
('Ácido fólico', 0, NULL, CURRENT_TIMESTAMP),
('Atorvastatina', 0, NULL, CURRENT_TIMESTAMP),
('Simvastatina', 0, NULL, CURRENT_TIMESTAMP),
('Prednisona', 0, NULL, CURRENT_TIMESTAMP),
('Clonazepam', 0, NULL, CURRENT_TIMESTAMP),
('Sertralina', 0, NULL, CURRENT_TIMESTAMP),
('Fluoxetina', 0, NULL, CURRENT_TIMESTAMP),
('Hidroclorotiazida', 0, NULL, CURRENT_TIMESTAMP);